import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  UserButton,
  SignIn,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import Header from "./components/Header";
import {
  SourceContextProvider,
  useSourceContext,
} from "./context/SourceContext";
import { DestinationContextProvider } from "./context/DestinationContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SourceContextProvider>
      <DestinationContextProvider>
        <ClerkProvider>
          <html lang="en">
            <body className={inter.className}>
              <Header className="flex justify-between">
                <h1>Clover Corp</h1>
                <UserButton showName />
              </Header>

              <main>
                <SignedOut>
                  <SignIn routing="hash" />
                </SignedOut>
                <SignedIn>{children}</SignedIn>
              </main>
            </body>
          </html>
        </ClerkProvider>
      </DestinationContextProvider>
    </SourceContextProvider>
  );
}
